image:
      file: .gitpod.dockerfile



tasks:
  - command: npm install -g generator-jhipster 





vscode:
  extensions:
    - mhutchie.git-graph@1.18.0:LzqJ/RuqakaRZud6LtvTQw==
    - vector-of-bool.gitflow@1.2.1:PMW+5uFLySIkcokoRjBGQQ==
