image:
      file: .gitpod.dockerfile



#tasks:
  #- command: npm install -g generator-jhipster 





vscode:
  extensions:
    - vector-of-bool.gitflow@1.2.1:PMW+5uFLySIkcokoRjBGQQ==
    - vscjava.vscode-maven@0.19.1:BvBDxQECRYP8SiCZ8Csrsg==
    - Pivotal.vscode-boot-dev-pack@0.0.8:BrfHu4se+ljgyUPUU+95ig==
