version: '3'

services:
jhipster:
   extends:
    image:
      file: .gitpod.yml
    service: jhipster
    ports:
      - 8000:8000
    networks:
      - compose-network  





  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Root123!"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - /mysql
    networks:
      - compose-network
      
     
      
      
      
      networks: 
  compose-network:
    driver: bridge
