version: '3'

services:






  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Root123!"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - /mysql
    networks:
      - compose-network
      
     
      
      
      
      networks: 
  compose-network:
    driver: bridge
